
before_script:
  - go get -v -x -d -t ./...

stages:
  - test

test_linux:
  stage: test
  tags:
    - linux
  script:
    - go test -v -x ./...

test_win32:
  stage: test
  tags:
    - win32
  script:
    - go test -v -x ./...
