language: go
go: 1.5.1
env:
  - GIMME_OS=linux GIMME_ARCH=386
  - GIMME_OS=linux GIMME_ARCH=amd64
  - GIMME_OS=darwin GIMME_ARCH=amd64
  - GIMME_OS=windows GIMME_ARCH=amd64
install:
  - go get -d -v ./...
script:
  - go build -v ./...
before_deploy:
  - mkdir build
  - cp butler butler.exe build/
deploy:
  provider: s3
  access_key_id: AKIAJC6IFO2T5RCEHRGA
  secret_access_key:
    secure: ajjDMCL07v8pdti4j7KP0XWR/Jnld/7igKlW52AlBovqj5z2xOjY8kqSylu/gTdP1XRtDzoSQrH8ZLCT4v1eGr+QWxcIiWcNKbpkCY9nkc8S0Ovdr1poUrx9wDQUU7V351Pd7+nUGjM3ZPuvBOTJxlGcr2x4pdL1ad6CmJ+NyZlY2+uNJ5r1o/OS5iqF9RMasbT9Tlr4xkcPPxCdWZ/Bn6tIiwpxSOZ9cFo1cyihC5QaWP0lB9uNdL57MWkSRH0jYGRaBmj7pol09C/GUVM0AjNbJNb04J+UG2dK3etLgvkIRZSxo8tXjBEZcCP3Uq8RJ3zCha76b38aCOPo7iylf1CfHko73EaHXRg+ShH9SThq2BSvD8hwsLEX4xe31WtRWKAH3qSXeubpYDuNfqrB1TBqO6dVy7A5aoiQdMob7Styqca+IwaDgPIRzY743oUk4S8ZFMpZgEbswaUtPVy/TOxqionBInPuFNRhb0mnLijc0p/EeXZsVfcwH4OcXaRCKSNkR9SYTmZqPeevCZ1069XR1/chRWukKieMbtCIFpubngXs+XhUfd3qXUStqOcdf0GMM5QrLv0a7Fqhim3jKQw+uTVOgvXaTIT6YpLG4+TblmAMyc/CYkCtxSLgUy9dPZ6Df4v87xh3JUjCB2l0PYZzJHQ5QtnVSuoWpNv3O8o=
  bucket: misc.amos.me
  region: us-east-1
  upload-dir: butler/$TRAVIS_TAG/$GIMME_OS-$GIMME_ARCH
  local_dir: build
  acl: public
  skip_cleanup: true
  on:
    tags: true
    repo: itchio/butler

