language: go
go: 1.5.1

matrix:
  include:
    - os: osx
      env: GIMMEOS=darwin GIMMEARCH=amd64
    - os: linux
      env: GIMMEOS=linux GIMMEARCH=386
      addons:
        apt:
          packages:
            - p7zip-full
            - gcc-multilib
    - os: linux
      env: GIMMEOS=linux GIMMEARCH=amd64
      addons:
        apt:
          packages:
            - p7zip-full
    - os: linux
      env: GIMMEOS=windows GIMMEARCH=386 CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++
      addons:
        apt:
          packages:
            - p7zip-full
            - mingw-w64
    - os: linux
      env: GIMMEOS=windows GIMMEARCH=amd64 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++
      addons:
        apt:
          packages:
            - p7zip-full
            - mingw-w64
install:
  - go get -d -v ./...
script:
  - "[ -z $TRAVIS_TAG ] || export BUTLER_LDFLAGS=\"-X main.version=$TRAVIS_TAG\""
  - "go get github.com/mitchellh/gox"
  - "export OSARCH=$GIMMEOS/$GIMMEARCH"
  - "[ \"$GIMMEOS\" = \"windows\" ] && export BUTLER_LDFLAGS=\"$BUTLER_LDFLAGS -extldflags=-Wl,--allow-multiple-definition\" || echo \"Not on windows.\""
  - "gox -osarch \"$OSARCH\" -ldflags \"$BUTLER_LDFLAGS\" -cgo -output=\"butler\""
before_deploy:
  - mkdir -p build
  - "cp butler build/ || :"
  - "cp butler.exe build/ || :"
  - mkdir -p dist
  - (cd dist && 7za a butler.7z ../build/*)
  - mkdir -p meta
  - echo $TRAVIS_TAG > meta/LATEST
deploy:
  - provider: s3
    access_key_id: AKIAJC6IFO2T5RCEHRGA
    secret_access_key:
      secure: ajjDMCL07v8pdti4j7KP0XWR/Jnld/7igKlW52AlBovqj5z2xOjY8kqSylu/gTdP1XRtDzoSQrH8ZLCT4v1eGr+QWxcIiWcNKbpkCY9nkc8S0Ovdr1poUrx9wDQUU7V351Pd7+nUGjM3ZPuvBOTJxlGcr2x4pdL1ad6CmJ+NyZlY2+uNJ5r1o/OS5iqF9RMasbT9Tlr4xkcPPxCdWZ/Bn6tIiwpxSOZ9cFo1cyihC5QaWP0lB9uNdL57MWkSRH0jYGRaBmj7pol09C/GUVM0AjNbJNb04J+UG2dK3etLgvkIRZSxo8tXjBEZcCP3Uq8RJ3zCha76b38aCOPo7iylf1CfHko73EaHXRg+ShH9SThq2BSvD8hwsLEX4xe31WtRWKAH3qSXeubpYDuNfqrB1TBqO6dVy7A5aoiQdMob7Styqca+IwaDgPIRzY743oUk4S8ZFMpZgEbswaUtPVy/TOxqionBInPuFNRhb0mnLijc0p/EeXZsVfcwH4OcXaRCKSNkR9SYTmZqPeevCZ1069XR1/chRWukKieMbtCIFpubngXs+XhUfd3qXUStqOcdf0GMM5QrLv0a7Fqhim3jKQw+uTVOgvXaTIT6YpLG4+TblmAMyc/CYkCtxSLgUy9dPZ6Df4v87xh3JUjCB2l0PYZzJHQ5QtnVSuoWpNv3O8o=
    bucket: misc.amos.me
    upload-dir: butler/$GIMME_OS-$GIMME_ARCH/$TRAVIS_TAG
    local_dir: dist
    acl: public_read
    skip_cleanup: true
    on:
      tags: true
      repo: itchio/butler
  - provider: s3
    access_key_id: AKIAJC6IFO2T5RCEHRGA
    secret_access_key:
      secure: ajjDMCL07v8pdti4j7KP0XWR/Jnld/7igKlW52AlBovqj5z2xOjY8kqSylu/gTdP1XRtDzoSQrH8ZLCT4v1eGr+QWxcIiWcNKbpkCY9nkc8S0Ovdr1poUrx9wDQUU7V351Pd7+nUGjM3ZPuvBOTJxlGcr2x4pdL1ad6CmJ+NyZlY2+uNJ5r1o/OS5iqF9RMasbT9Tlr4xkcPPxCdWZ/Bn6tIiwpxSOZ9cFo1cyihC5QaWP0lB9uNdL57MWkSRH0jYGRaBmj7pol09C/GUVM0AjNbJNb04J+UG2dK3etLgvkIRZSxo8tXjBEZcCP3Uq8RJ3zCha76b38aCOPo7iylf1CfHko73EaHXRg+ShH9SThq2BSvD8hwsLEX4xe31WtRWKAH3qSXeubpYDuNfqrB1TBqO6dVy7A5aoiQdMob7Styqca+IwaDgPIRzY743oUk4S8ZFMpZgEbswaUtPVy/TOxqionBInPuFNRhb0mnLijc0p/EeXZsVfcwH4OcXaRCKSNkR9SYTmZqPeevCZ1069XR1/chRWukKieMbtCIFpubngXs+XhUfd3qXUStqOcdf0GMM5QrLv0a7Fqhim3jKQw+uTVOgvXaTIT6YpLG4+TblmAMyc/CYkCtxSLgUy9dPZ6Df4v87xh3JUjCB2l0PYZzJHQ5QtnVSuoWpNv3O8o=
    bucket: misc.amos.me
    upload-dir: butler/$GIMME_OS-$GIMME_ARCH
    local_dir: meta
    acl: public_read
    skip_cleanup: true
    on:
      tags: true
      repo: itchio/butler
  
  
